---
- name: Register maquinas
  hosts: automationcontroller
  gather_facts: false

  vars:
    aap_setup_prep_setup_dir: /opt/aap/
    aap_backup_dest: /root/backups

  pre_tasks:
    - name: Create backup directory
      ansible.builtin.file:
        state: directory
        path: "{{ aap_backup_dest }}"
        owner: root
        group: root
        mode: '0755'
  tasks:
    - name: Backup
      ansible.builtin.import_role:
        name: infra.aap_utilities.aap_backup

    - name: Find all files that are older than 10 days
      ansible.builtin.find:
        paths: "{{ aap_backup_dest }}"
        age: 3d
        recursive: true
      register: filesOlderThan

    - name: Remove older than 10
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ filesOlderThan.files }}"
