---
- name: Register maquinas
  hosts: automationcontroller
  gather_facts: false

  vars:
    aap_setup_prep_setup_dir: /opt/aap/
    aap_backup_dest: /root/backups

  pre_tasks:
    - name: Create backup directory
      ansible.builtin.file:
        state: directory
        path: "{{ aap_backup_dest }}"
        owner: root
        group: root
        mode: '0755'
  tasks:
    - name: Backup
      ansible.builtin.import_role:
        name: infra.aap_utilities.aap_backup
    
    - name: comando localhost
      ansible.builtin.shell: ls -lh "{{ aap_setup_prep_setup_dir }}"
      register: ls
    
    - name: debug
      ansible.builtin.debug:
        var: ls

