# Playbook to backup Automation controller
---
- name: Create backup directory
  ansible.builtin.file:
    state: directory
    path: "{{ aap_backup_dest }}"
    owner: root
    group: root
    mode: '0755'

- name: Backup
  ansible.builtin.import_role:
    name: infra.aap_utilities.aap_backup
