---

- name: Create Credentials AcessoHosts
  ansible.controller.credential:
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    controller_host: "{{ controller_host }}"
    validate_certs: "{{ validate_certs }}"
    name: AcessoHosts
    credential_type: Machine
    organization: "{{ organization }}"
    description: "{{ description_project }}"
    state: "{{ config_aap_estado }}"
    inputs:
      username: root
      password: redhat

- name: Create Credentials vault
  ansible.controller.credential:
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    controller_host: "{{ controller_host }}"
    validate_certs: "{{ validate_certs }}"
    name: AcessoVaultVars
    credential_type: Vault
    organization: "{{ organization }}"
    description: "{{ description_project }}"
    state: "{{ config_aap_estado }}"
    inputs:
      vault_password: 'new_password'
